### PR TITLE
Update dependencies, travis and fix test

### PR DESCRIPTION
**Pull request by piwonesien**
- Update some dependencies
- Fix zip-file downloader for not existing zip files
- Remove deprecated options in test

### CODE REVIEW

**Comment by piwonesien** [comment]
also fix the deprecation warning of archive.bulk() (#462)

**Comment by piwonesien** [comment]
hmm, travis crashed here o.O I think it's a travis problem, I've run the same commit in my repo & there travis has no problems ...
https://travis-ci.org/piwonesien/nw-builder/jobs/357921814 -> this pr works
https://travis-ci.org/nwjs-community/nw-builder/jobs/357921882 -> this pr fails

**Comment by davedoesdev** [comment]
This would also bring in a newer version of hoek, which has a vulnerability < 4.2.1
https://nodesecurity.io/advisories/566

**Comment by f3l1x** [comment]
Hi, any updates?

**Comment by kessler** [comment]
@f3l1x  Will publish to npm asap

**Pull request merged**
